In [5]:
import pandas as pd
df = pd.read_csv("/content/WA_Fn-UseC_-Telco-Customer-Churn.csv")

In [7]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [10]:
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'],errors='coerce')

In [12]:
df= df.dropna()

In [14]:
df['Churn'].value_counts(normalize=True)

Churn
No     0.734215
Yes    0.265785
Name: proportion, dtype: float64

In [16]:
#Churn rate overall
df['Churn'].value_counts(normalize=True)*100

Churn
No     73.421502
Yes    26.578498
Name: proportion, dtype: float64

In [18]:
#Churn by Tenure
df.groupby('tenure')['Churn'].value_counts(normalize=True).unstack()

Churn         No       Yes
tenure
1       0.380098  0.619902
2       0.483193  0.516807
3       0.530000  0.470000
4       0.528409  0.471591
5       0.518797  0.481203
...          ...       ...
68      0.910000  0.090000
69      0.915789  0.084211
70      0.907563  0.092437
71      0.964706  0.035294
72      0.983425  0.016575

[72 rows x 2 columns]

In [22]:
df['tenure_group'] = pd.cut(df['tenure'], bins = [0,12,24,48.72])
df.groupby('tenure_group')['Churn'].value_counts(normalize=True).unstack()

/tmp/ipykernel_2083/3435788579.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('tenure_group')['Churn'].value_counts(normalize=True).unstack()

Churn                No       Yes
tenure_group
(0.0, 12.0]    0.523218  0.476782
(12.0, 24.0]   0.712891  0.287109
(24.0, 48.72]  0.796110  0.203890

In [28]:
#Churn by Monthly Charges
df.groupby('Churn')['MonthlyCharges'].mean()

Churn
No     61.307408
Yes    74.441332
Name: MonthlyCharges, dtype: float64

In [26]:
#Churn by Contract Type
df.groupby('Contract')['Churn'].value_counts(normalize=True).unstack()

Churn                 No       Yes
Contract
Month-to-month  0.572903  0.427097
One year        0.887228  0.112772
Two year        0.971513  0.028487

In [27]:
#Churn by Payment Method
df.groupby('PaymentMethod')['Churn'].value_counts(normalize=True).unstack()

Churn                            No       Yes
PaymentMethod
Bank transfer (automatic)  0.832685  0.167315
Credit card (automatic)    0.847469  0.152531
Electronic check           0.547146  0.452854
Mailed check               0.807980  0.192020